# Generated by Django 6.0 on 2026-05-03 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0005_alter_sellerprofile_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icecat_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mpn', models.CharField(blank=True, help_text='Manufacturer Part Number', max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('GPU', 'Graphics Card'), ('CPU', 'Processor'), ('RAM', 'Memory'), ('MOBO', 'Motherboard'), ('SSD', 'Solid State Drive'), ('PSU', 'Power Supply'), ('CASE', 'Casing'), ('COOLER', 'CPU Cooler')], max_length=20)),
                ('stock_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('specs_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Master Product',
                'unique_together': {('brand', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Listing Title', max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Direct Buy Price', max_digits=12)),
                ('condition', models.CharField(choices=[('NEW', 'Brand New'), ('USED_LIKE_NEW', 'Used - Like New'), ('USED_GOOD', 'Used - Good'), ('USED_FAIR', 'Used - Fair')], default='USED_GOOD', max_length=20)),
                ('actual_photo_1', models.ImageField(upload_to='listings/actual/')),
                ('actual_photo_2', models.ImageField(blank=True, null=True, upload_to='listings/actual/')),
                ('actual_photo_3', models.ImageField(blank=True, null=True, upload_to='listings/actual/')),
                ('is_bidding_enabled', models.BooleanField(default=False)),
                ('starting_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_highest_bid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bid_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.masterproduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='products.productlisting')),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
