# Generated by Django 6.0 on 2026-05-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_order_product_alter_trade_product'),
        ('products', '0002_remove_product_category_masterproduct_productlisting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
