# Generated by Django 6.0 on 2026-05-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='category',
            field=models.CharField(choices=[('GPU', 'Graphics Card'), ('CPU', 'Processor'), ('RAM', 'Memory'), ('MOBO', 'Motherboard'), ('SSD', 'Solid State Drive'), ('HDD', 'Hard Disk Drive'), ('PSU', 'Power Supply'), ('CASE', 'Casing'), ('COOLER', 'CPU Cooler')], max_length=20),
        ),
    ]
