# Generated by Django 6.0 on 2026-05-05 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_masterproduct_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlisting',
            old_name='is_bidding_enabled',
            new_name='has_warranty',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='actual_photo_1',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='actual_photo_2',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='actual_photo_3',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='bid_end_time',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='current_highest_bid',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='title',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='warranty_info',
            field=models.TextField(blank=True, help_text="What is/isn't included", null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in months', null=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Brand New'), ('OPEN', 'Open Box'), ('USED', 'Used')], default='USED', max_length=10),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='description',
            field=models.TextField(help_text='Describe the specific condition/history of your item'),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='master_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to='products.masterproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
