# Generated by Django 6.0 on 2026-05-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_buyerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerProfile',
        ),
    ]
