# Generated by Django 6.0 on 2026-05-03 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('products', '0002_remove_product_category_masterproduct_productlisting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productlisting'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productlisting'),
        ),
    ]
