# Generated by Django 6.0 on 2026-05-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_buyorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyorder',
            options={'ordering': ['-bid_price']},
        ),
    ]
