# Generated by Django 6.0 on 2026-04-08 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PROFESSIONAL', 'Professional')], default='INDIVIDUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('ntn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to='verification/cnic/')),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to='verification/cnic/')),
                ('selfie_with_id', models.ImageField(blank=True, null=True, upload_to='verification/selfies/')),
                ('shop_photo', models.ImageField(blank=True, null=True, upload_to='verification/shops/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
