# Generated by Django 6.0 on 2026-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sellerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='selfie_with_id',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
