# Generated by Django 6.0 on 2026-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_sellerprofile_selfie_with_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='face_photo',
            field=models.ImageField(null=True, upload_to='verification/faces/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='nickname',
            field=models.CharField(default='', help_text='Display Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='province',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='cnic_back',
            field=models.ImageField(null=True, upload_to='verification/cnic/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='cnic_front',
            field=models.ImageField(null=True, upload_to='verification/cnic/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='cnic_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='father_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_address',
            field=models.TextField(default='', help_text='Used for Shop Address or Residential Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
    ]
