# Generated by Django 6.0 on 2026-05-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sellerprofile_face_photo_sellerprofile_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='nickname',
            field=models.CharField(help_text='Display Name', max_length=100, unique=True),
        ),
    ]
